### ISSUE TITLE
xml parsing error for xbrlCIKLookup

### ISSUE THREAD

**Issue by SteveBronder** [bergant/xbrlus#10]
I'm getting the following when running the example in the readme.md
```R
library(xbrlus)
> companies <- xbrlCIKLookup(c(
+   "aapl", 
+   "goog", 
+   "fb"
+ ))
# Extra content at the end of the document
# Error: 1: Extra content at the end of the document
```

I'm guessing they switched something up with the doc

**Comment by bergant** [comment]
Is this still a problem? I can't reproduce the error on my machine...

**Comment by SteveBronder** [comment]
Sorry, I actually can't reproduce this on my machine either so I probably goofed
