### ISSUE TITLE
Error in xbrlBaseElement: rbind fails due to mismatched columns

### ISSUE THREAD

**Issue by SteveBronder** [bergant/xbrlus#3]
The following xbrlBaseElement call returns an error due to their being a balance variable in EarningsPerShareBasicAndDiluted, but not in OtherNonoperatingIncome

```
xbrlBaseElement(c("OtherNonoperatingIncome","EarningsPerShareBasicAndDiluted" ))
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```

I'm not sure if this is kosher, but one possible fix is to add a balance variable for the element that does not have one such as the following.

```
xbrlBaseElement <- function (Element, Namespace = NULL, as_data_frame = TRUE) {
  if (length(Element) > 1) {
    return(do.call(base::rbind, c(lapply(Element, xbrlBaseElement, 
                                   Namespace = Namespace, as_data_frame = as_data_frame), 
                            make.row.names = FALSE)))
  }
  ret <- xbrlus_get("xbrlBaseElement", list(Element = Element, 
                                            Namespace = Namespace))
  if (as_data_frame) {
    ret <- xbrlus_to_data_frame(ret, "baseElement")
   # Add balance if it does not exist
    if (!("balance" %in% colnames(ret))) ret$balance <- NA
  }
  ret
}
```

**Comment by SteveBronder** [comment]
If adding balance is the route you choose I think about adding a note in the docs

**Comment by bergant** [comment]
I think I'll just use `merge` with `all = TRUE` instead of `rbind`. You never know which field could be missing in xbrlus database and merge fills `NA`s by default. Not as efficent as rbind but this operation does not expect more than a few elements.

Thanks for finding this.
