### ISSUE TITLE
Error: Get call in xbrlus_get long URI

### ISSUE THREAD

**Issue by SteveBronder** [bergant/xbrlus#4]
This my be a non-issue and me just breaking the package. I'm attempting to call xbrlValues with a large amount of elements (951). When I run the function it returns the following error

```
 values <- xbrlValues(CIK = table_companies[, "CIK"],
                         Element = elements[,"elementName"],
                         DimReqd = FALSE,
                         Ultimus = TRUE,
                         Small = TRUE, 
                         Period = "1Q",
                         Year = 2016,
                         as_data_frame = TRUE)
Space required after the Public Identifier
SystemLiteral " or ' expected
SYSTEM or PUBLIC, the URI is missing
Error: 1: Space required after the Public Identifier
2: SystemLiteral " or ' expected
3: SYSTEM or PUBLIC, the URI is missing
```

Tracing through the code it appears the error comes from xbrlus_get, specifically in `xbrlus_validate(res)`.  It appears that the URI given by `httr::GET(xbrlus_url, query = query)` brings back something with

```
<title>414 Request-URI Too Large</title>
</head><body>
<h1>Request-URI Too Large</h1>
```

So this appears to be an httr problem more than an xbrlus problem. This stackoverflow problem covers the issue and it appears to be a problem with how the php is written.
[here](http://stackoverflow.com/questions/2891574/how-do-i-resolve-a-http-414-request-uri-too-long-error).

The only thing I can think of to fix this in xbrlus would be to check whether res status code is 414 and if so, break up the query in multiple queries, run them, then bind them all together at the end.

If you know a workaround so I can get all information from a given companies 10-Q, that would solve my problem and this can be possibly moved over to httr.

**Comment by bergant** [comment]
You could call xbrlus once per cik and join the results afterwards.
Use `lapply` to loop over cik vector and join a list of data frames with `rbind`. For example:

```
values_list <- lapply( companies$cik, 
   function(x) {
    xbrlValues(
        CIK = x, 
        Element = elements$elementName, 
        DimReqd = FALSE, 
        Period = "Y",
        Year = 2013,
        NoYears = 1,
        Ultimus = TRUE,
        Small = TRUE,
        as_data_frame = TRUE
      )
   })

values <- do.call(rbind, values_list)
```

I used variables from my readme file example, but I guess it should be easy to translate it to your case.

**Comment by SteveBronder** [comment]
Still the same issue. I think this is an issue with how httr makes get requests. [Here](https://gist.githubusercontent.com/Stevo15025/3b91483fc9a853f969bd/raw/3d850796965ac4fc9595db58b3c9a8b8f14d4938/element_bank.csv) is a csv of the elements I am using. You can see it's pretty large and I'm pretty sure it's breaking some rules somewhere about making this large of a query, even by individual company.

**Comment by bergant** [comment]
Then just split your elements to a few packages of 100:

```
element_list <- split(elements$elementName, (1:nrow(elements)) %/% 100 )
values_list <- lapply(element_list, function(els) {

  xbrlValues(CIK = companies$cik[1],
                     Element = els,
                     DimReqd = FALSE,
                     Ultimus = TRUE,
                     Small = TRUE, 
                     Period = "1Q",
                     Year = 2016,
                     as_data_frame = TRUE)
})  

df_values <- Reduce( function(x, y) merge(x, y, all = TRUE), values_list)
```

**Comment by SteveBronder** [comment]
Yes that is what I'm currently doing.
