### ISSUE TITLE
xbrlCIKLookup Broken

### ISSUE THREAD

**Issue by SteveBronder** [bergant/xbrlus#8]
Hello again! From the tutorial

```R
library(xbrlus)
companies <- xbrlCIKLookup(c(
    "aapl", 
    "goog", 
    "fb"
))
# Error: Returned message is not an xml
```

**Comment by SteveBronder** [comment]
Ah, in xbrlus [line 65](https://github.com/bergant/xbrlus/blob/master/R/xbrlus.R#L65) that if statement should just check if 'text/xml' is inside of the content type and not for exactness. Something has changed and `res$headers$`content-type` is now

```
"text/xml;charset=UTF-8"
```

which should be valid.

I can make a patch if you like, though it may be easier for you to change line 65 to 

```
if (!grepl(pattern = "text/xml",x = res$headers$`content-type`, fixed = TRUE)) {
...
}
```

**Comment by bergant** [comment]
I changed the content type validation. Thank you for reporting this.
